services:
  db:
    container_name: mysql_db
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: "Asia/Seoul"
    platform: linux/x86_64
    restart: always

  app:
    container_name: app
    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: mysql_db

volumes:
  db_data:

