spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:local;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true


#logging:
#  level:
#    root: info


openai:
  model: gpt-3.5-turbo-0125
  secret-key: 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
  max-token: 300
  temperature: 0.0
  top-p: 1.0
  media-type: "application/json; charset=UTF-8"
  url: "https://api.openai.com/v1/chat/completions"

jwt:
  secret-key: FyaiSqfBXkcutzm08RK5dKalHtx4IDOxoh-kSuxGp5s=r
  expiration-period-milliseconds: 1800000