name: Java CD Gradle and Docker - develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Setting application.yml
        run: |
          cd ./src/main/resources
          echo "${{ secrets.APPLICATION_DEV_YML }}" > ./application-dev.yml

      - name: Grant permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: |
          ./gradlew build -x test

      - name: Docker image build and push to docker hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }} .
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}

  deploy:
   needs: build
   runs-on: ubuntu-latest

   steps:
   - name: Deploy to NCP Server
     uses: appleboy/ssh-action@master

     with:
       host: ${{ secrets.NCP_HOST }}
       username: ${{ secrets.NCP_USERNAME }}
       password: ${{ secrets.NCP_PASSWORD }}
       port: ${{ secrets.NCP_PORT }}
       script: |
         cd /home/sonmong-backend
         git remote update
         git checkout .
         git checkout develop
         git pull
         echo "${{ secrets.DOCKER_COMPOSE_DEV_YML }}" > ./docker-compose.yml
         echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
         sudo docker compose stop app
         sudo docker compose rm -f app
         sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}
         sudo docker compose up -d app
         sudo docker image prune -f